### ISSUE TITLE
[BUG] Confusion when building for iOS/How AdMob works on iOS

### ISSUE THREAD

**Issue by sjhennion** [Poing-Studios/Godot-AdMob-Android-iOS#36]
**Describe the bug**
I've ran into some issues when trying to build for iOS.  This section is confusing me

```Copy the library libgodot.iphone.release.fat.a you have downloaded from releases tab inside the exported Xcode project. You must override the '.a' file with "your_project_name", should be like: 'your_project_name.a'.```

I'm not sure what it means.  I took it to mean I had to copy `libgodot.iphone.release.fat.a` into the project, and then rename it the name of my project, but that didn't work, and then I realized there was already a `my_project_name.a` in the project.  

If I don't copy `libgodot.iphone.release.fat.a` into my project, it builds and runs (although it doesn't currently work), but if I add `libgodot.iphone.release.fat.a` I get compiler errors about duplicate symbols.  

However, if I remove `my_project_name.a` from the directory, it complains about it missing.  I tried removing `my_project_name.a`, and renaming `libgodot.iphone.release.fat.a` into `my_project_name.a`, but that leads build errors with some of the Google frameworks.

At this point I'm just unsure about what exactly I'm supposed to be doing with `libgodot.iphone.release.fat.a` and `my_project_name.a`

**To Reproduce**
Just try and build iOS as described.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - Xcode: 11.2.1
 - iOS Version: 13.3

**Comment by gustavottc** [comment]
Hey, I'm occupied right now, in a few hours I will explain better

**Comment by sjhennion** [comment]
@gustavottc No rush, I won't be able to try anything until around 8PM EST anyway.

**Comment by gustavottc** [comment]
I tried here, you need to copy the frameworks inside your Xcode project, like this: 

![Captura de Tela 2021-01-06 às 13 40 26](https://user-images.githubusercontent.com/20030153/103795860-45cce500-5025-11eb-87ac-18ef6c6c85c2.png)

![Captura de Tela 2021-01-06 às 13 38 27](https://user-images.githubusercontent.com/20030153/103795850-42395e00-5025-11eb-88e8-c7ff413c7434.png)


Don't forget to:
![Captura de Tela 2021-01-06 às 13 28 07](https://user-images.githubusercontent.com/20030153/103795982-6bf28500-5025-11eb-8b8b-226bafeddc08.png)
![Captura de Tela 2021-01-06 às 13 29 00](https://user-images.githubusercontent.com/20030153/103795987-6d23b200-5025-11eb-8151-f941fc3c4b6c.png)
![Captura de Tela 2021-01-06 às 13 32 18](https://user-images.githubusercontent.com/20030153/103795992-6dbc4880-5025-11eb-8a1a-e6683033336d.png)


And if you want to try run on simulator, check this issue: https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aclosed+simulator

If still doesn't work please let me know

**Comment by sjhennion** [comment]
Does anything need to be done with libgodot.iphone.release.fat.a?

**Comment by gustavottc** [comment]
@sjhennion yes, you still need to replace to the .a file of your game, just like you did:

```However, if I remove my_project_name.a from the directory, it complains about it missing. I tried removing my_project_name.a, and renaming libgodot.iphone.release.fat.a into my_project_name.a, but that leads build errors with some of the Google frameworks.```

**Comment by gustavottc** [comment]
The build erros of Google framework are solved doing the steps that I mentioned above

**Comment by sjhennion** [comment]
I think I'm still missing something here @gustavottc.

I started from scratch, and followed your steps above.  After completing those steps, I built the project, and it built successfully, but I didn't try running just yet.

I then removed `my_project_name.a` from the directory, placed `libgodot.iphone.release.fat.a` into the directory, and renamed it `my_project_name.a`, and that resulted in the some of the build errors I was seeing yesterday:

![image](https://user-images.githubusercontent.com/482282/103844221-687fed80-5067-11eb-98b3-61ecfcc6788c.png)

**Comment by gustavottc** [comment]
You need to place the framework AppTrackingTransparency, but as "Optional" just like the second picture that i send:
![image](https://user-images.githubusercontent.com/20030153/103848683-b0137300-5081-11eb-9d2b-9ff7d0a3108c.png)

This "___darwin_check_fd_set_overflow" i never saw that, just make sure to add these frameworks like the picture above

**Comment by gustavottc** [comment]
The UniformTypeIdentifiers, i never needed to add, but try to add to see if works, i guess it only missing these frameworks to work your AdMob

**Comment by gustavottc** [comment]
the explanation of starting to appear these errors in XCode after changing the '.a' file is that: this '.a' file is Godot's binary, for example, it is Godot itself where the phone runs the game based on binary, this binary is modified and contains the AdMob change inside it, but for AdMob to work it needs some frameworks and some extra settings like change the .plist which is what you are doing, it is boring to do today, but it is the only one way.

In the future I will include the new plugin system for iOS, which will work similarly to Android, that is, it will be much simpler, but it needs to be included in a new version of Godot for me to start working, it will probably only be possible in version 3.2.5 onwards

**Comment by sjhennion** [comment]
@gustavottc Thanks for the explanation, that makes it much clearer as to what's going on.

It looks like UniformTypeIdentifiers.framework is also only available as of iOS 14+, so I think my issue is pretty clear at this point, I need to upgrade Xcode and the iOS SDK.

**Comment by gustavottc** [comment]
@sjhennion but this is a Warning, you can ignore this, the error is because is missing the AppTrackingTransparency.framework  ([ATTrackingManager](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager)) as "optional"

![Captura de Tela 2021-01-07 às 11 13 13](https://user-images.githubusercontent.com/20030153/103902480-58085b00-50d9-11eb-82a4-5638d2abb989.png)

As you can see, i can use the AdMob on iOS 13.0 on Simulator without these erros

![Captura de Tela 2021-01-07 às 11 14 00](https://user-images.githubusercontent.com/20030153/103902628-8ede7100-50d9-11eb-92a2-50330f210bf5.png)

By the way, this is my XCode version: Version 12.3 (12C33)

**Comment by sjhennion** [comment]
I must still need to upgrade something, it's possible I'm a few versions back, because I don't even have AppTrackingTransparency available as a linkable binary.  Will have to get back to this later tonight.  Thanks again for all the help!

**Comment by sjhennion** [comment]
@gustavottc Sorry, my MBP is older and only has 128gb of disk space, it was quite an effort to update to Big Sur and get Xcode 12.3 installed.  But, everything is updated and the example project is working now, and I've got ads!

Only thing is I'm seeing this spammed to the log multiple times a second:
<img width="735" alt="Screen Shot 2021-01-08 at 8 58 42 PM" src="https://user-images.githubusercontent.com/482282/104080189-a3635c00-51f4-11eb-91bc-0857b68b49e2.png">

**Comment by gustavottc** [comment]
Are you testing on a Real Device? What's the version of your iOS?

**Comment by gustavottc** [comment]
Ok, i saw here: iOS Version: 13.3

Unfortunately this error is related to the iOS version less than 13.4, and not exclusive to AdMob: https://stackoverflow.com/questions/58321114/why-i-get-the-console-warning-process-kill-returned-unexpected-error- 1-when

Try to update your phone or run on a simulator, don't worry about these messages

**Comment by gustavottc** [comment]
On 13.0 Simulator these errors doesn't appear for me

![Captura de Tela 2021-01-08 às 23 18 22](https://user-images.githubusercontent.com/20030153/104080608-debb5600-5207-11eb-8eed-ddad9c61d5d8.png)

**Comment by sjhennion** [comment]
@gustavottc that explains it, I'm on 13.3

Thanks again for all the help, really appreciate it!  I saw you added the [Feature] for the wiki, not sure whether you were going to do a first pass of getting information in there, but I'd be happy to add more details in based on my findings.

**Comment by gustavottc** [comment]
@sjhennion i put right now the Wiki to be editable to public it would be amazing if you contributed to the Wiki

Or even if you have something that you think needs to be improved in Readme.md, you can create a PR and I will commit

I will clone the issue since the problem was solved, thanks!
